window.TOURISM_DATA = {
  destinations: [
    {
      slug: "west-lake",
      name: "杭州西湖",
      city: "杭州",
      province: "浙江",
      region: "华东",
      tag: "山水",
      season: "春秋",
      duration: "2-3天",
      budget: "800-1500元",
      popularity: 98,
      featured: true,
      image: "https://commons.wikimedia.org/wiki/Special:FilePath/West_Lake_Pavilion_and_Water_Lilies,_Hangzhou_120529_1.jpg",
      gallery: [
        "https://commons.wikimedia.org/wiki/Special:FilePath/West_Lake_Pavilion_and_Water_Lilies,_Hangzhou_120529_1.jpg",
        "https://commons.wikimedia.org/wiki/Special:FilePath/Leifeng_Pagoda_DJI_0593_%282%29.jpg",
      ],
      coordinates: { lat: 30.2360517, lng: 120.1501183 },
      overview:
        "西湖是杭州最具代表性的城市名片，湖岸、堤桥、古刹和茶园共同构成了很强的层次感。春天看花，秋天看湖，冬天也别有静气。",
      highlights: [
        { name: "苏堤春晓", desc: "适合清晨散步，光线柔和，照片最容易出彩。" },
        { name: "雷峰塔", desc: "看晚霞和湖面视角，适合安排在日落前后。" },
        { name: "断桥残雪", desc: "冬季和清晨来更有味道，和白堤一起走很舒服。" },
      ],
      foods: ["龙井虾仁", "东坡肉", "片儿川"],
      transport: ["地铁 1/2/5 号线换乘后步行可到部分湖区", "杭州东站到西湖景区约 30-40 分钟", "旺季建议地铁+步行，避免拥堵"],
      tips: ["骑行环湖更省时间", "雷峰塔和灵隐寺适合连着安排", "雨后湖景更通透"],
      nearby: ["灵隐寺", "孤山", "河坊街"],
      routeType: "city",
      sources: [
        "Wikimedia Commons 文件页：West Lake Pavilion and Water Lilies, Hangzhou 120529 1.jpg",
        "Wikimedia Commons 文件页中坐标信息：30°14'9.78601\"N, 120°9'0.42599\"E",
      ],
      label: "湖景与古典园林",
    },
    {
      slug: "forbidden-city",
      name: "北京故宫",
      city: "北京",
      province: "北京",
      region: "华北",
      tag: "古建",
      season: "四季",
      duration: "1-2天",
      budget: "500-1200元",
      popularity: 100,
      featured: true,
      image: "https://commons.wikimedia.org/wiki/Special:FilePath/Forbidden_City_%2854449398364%29.jpg",
      gallery: [
        "https://commons.wikimedia.org/wiki/Special:FilePath/Forbidden_City_%2854449398364%29.jpg",
        "https://commons.wikimedia.org/wiki/Special:FilePath/Forbidden_City_Beijing_%282%29.jpg",
      ],
      coordinates: { lat: 39.9143331, lng: 116.390219 },
      overview:
        "故宫是北京最经典的文化目的地之一，适合喜欢建筑、历史和展陈的人。路线非常清楚，但门票和安检都需要提前规划。",
      highlights: [
        { name: "午门", desc: "进入中轴线的起点，也是最有仪式感的位置。" },
        { name: "太和殿", desc: "中轴核心建筑，适合和讲解结合看格局。" },
        { name: "珍宝馆/钟表馆", desc: "室内展厅适合避开日晒，细看藏品更从容。" },
      ],
      foods: ["炸酱面", "北京烤鸭", "豆汁焦圈"],
      transport: ["地铁 1 号线天安门东/西站", "建议提前在线预约门票", "中轴线一日游可连天安门、景山、公园"],
      tips: ["尽量早入场，避开中午高峰", "鞋子要舒服", "讲解器很值"],
      nearby: ["景山公园", "天安门广场", "王府井"],
      routeType: "city",
      sources: [
        "Wikimedia Commons 文件页：Forbidden City (54449398364).jpg",
        "Wikimedia Commons 文件页中的坐标信息：39°54'51.599\"N, 116°23'24.788\"E",
      ],
      label: "中轴线与宫殿建筑",
    },
    {
      slug: "chengdu-panda",
      name: "成都大熊猫繁育研究基地",
      city: "成都",
      province: "四川",
      region: "西南",
      tag: "亲子",
      season: "秋冬",
      duration: "半天-1天",
      budget: "200-800元",
      popularity: 96,
      featured: true,
      image: "https://commons.wikimedia.org/wiki/Special:FilePath/Chengdu_Research_Base_of_Giant_Panda_Breeding,_201907,_10.jpg",
      gallery: [
        "https://commons.wikimedia.org/wiki/Special:FilePath/Chengdu_Research_Base_of_Giant_Panda_Breeding,_201907,_10.jpg",
        "https://commons.wikimedia.org/wiki/Special:FilePath/Chengdu_Research_Base_of_Giant_Panda_Breeding,_201907,_07.jpg",
      ],
      coordinates: { lat: 30.739308, lng: 104.140703 },
      overview:
        "这是成都最适合亲子和动物爱好者的目的地之一。清晨活跃度更高，安排上午入园更容易看到熊猫进食和活动。",
      highlights: [
        { name: "大熊猫馆", desc: "主看点，建议优先安排在开园后尽早进入。" },
        { name: "月亮产房", desc: "适合看幼年熊猫和科普展示。" },
        { name: "红熊猫活动区", desc: "节奏更轻松，拍照也很好看。" },
      ],
      foods: ["火锅", "钟水饺", "三大炮"],
      transport: ["地铁 3 号线转公交或打车", "清晨打车更省时间", "周边可顺路安排北湖或市区美食"],
      tips: ["越早越好", "带水和轻便外套", "注意不要用闪光灯"],
      nearby: ["青龙湖", "昭觉寺", "成都市区美食街"],
      routeType: "family",
      sources: [
        "Wikimedia Commons 机构页：Chengdu Research Base of Giant Panda Breeding",
        "Wikimedia Commons 文件页坐标：30°44'21.51\"N, 104°08'26.53\"E",
      ],
      label: "亲子与动物科普",
    },
    {
      slug: "gulangyu",
      name: "厦门鼓浪屿",
      city: "厦门",
      province: "福建",
      region: "华南",
      tag: "海岛",
      season: "春秋",
      duration: "1-2天",
      budget: "600-1400元",
      popularity: 95,
      featured: true,
      image: "https://commons.wikimedia.org/wiki/Special:FilePath/Gulangyu_Island_20191130144138.jpg",
      gallery: [
        "https://commons.wikimedia.org/wiki/Special:FilePath/Gulangyu_Island_20191130144138.jpg",
        "https://commons.wikimedia.org/wiki/Special:FilePath/Xiamen_-_View_from_GulangYu_20091120.jpg",
      ],
      coordinates: { lat: 24.449959, lng: 118.058236 },
      overview:
        "鼓浪屿的节奏很慢，适合喜欢散步、老建筑、海景和小店的人。岛上步行体验很强，拍照和随手看街景都很舒服。",
      highlights: [
        { name: "菽庄花园", desc: "园林和海景结合得很好，适合慢慢逛。" },
        { name: "钢琴博物馆", desc: "鼓浪屿的音乐标签很明显，值得安排。" },
        { name: "环岛路远眺", desc: "把海岸线和厦门市区一起收入镜头。" },
      ],
      foods: ["沙茶面", "海蛎煎", "土笋冻"],
      transport: ["厦门轮渡码头乘船上岛", "岛上以步行和电瓶车接驳为主", "建议带轻便包，不适合拖箱长走"],
      tips: ["最好提前订船票", "上午和傍晚最舒服", "岛内坡道较多，鞋子要稳"],
      nearby: ["中山路", "厦门大学", "环岛路"],
      routeType: "sea",
      sources: [
        "Wikimedia Commons 文件页：Gulangyu Island 20191130144138.jpg",
        "Wikimedia Commons 文件页坐标：24°26'59.85\"N, 118°03'29.65\"E",
      ],
      label: "海岛与老建筑",
    },
    {
      slug: "li-river",
      name: "桂林漓江",
      city: "桂林",
      province: "广西",
      region: "华南",
      tag: "山水",
      season: "春秋",
      duration: "1-2天",
      budget: "700-1600元",
      popularity: 97,
      featured: true,
      image: "https://commons.wikimedia.org/wiki/Special:FilePath/Guilin_Li_River.jpg",
      gallery: [
        "https://commons.wikimedia.org/wiki/Special:FilePath/Guilin_Li_River.jpg",
        "https://commons.wikimedia.org/wiki/Special:FilePath/Li_River_(47223037521).jpg",
      ],
      coordinates: { lat: 24.955108, lng: 110.45734 },
      overview:
        "漓江以喀斯特山水著称，船游和沿江骑行都很适合。天气好时山影和水面层次分明，是最容易拍出“桂林山水甲天下”感受的地方。",
      highlights: [
        { name: "漓江游船", desc: "经典路线，适合第一次来桂林的人。" },
        { name: "杨堤到兴坪", desc: "沿线风景最有代表性，适合取景。" },
        { name: "阳朔乡道", desc: "骑行和轻徒步都很舒服。" },
      ],
      foods: ["桂林米粉", "啤酒鱼", "田螺酿"],
      transport: ["桂林市区到码头可打车或乘景区接驳", "建议预留半天到一天", "晴天和雾天呈现完全不同的景色"],
      tips: ["雨后和清晨层次最好", "船游前后可顺路去阳朔", "防晒和防蚊都要准备"],
      nearby: ["阳朔", "象鼻山", "十里画廊"],
      routeType: "river",
      sources: [
        "Wikimedia Commons 文件页：Guilin Li River.jpg",
        "Wikimedia Commons 文件页坐标：24°57'18.39\"N, 110°27'26.42\"E",
      ],
      label: "喀斯特山水",
    },
    {
      slug: "yalong-bay",
      name: "三亚亚龙湾",
      city: "三亚",
      province: "海南",
      region: "华南",
      tag: "海岛",
      season: "冬春",
      duration: "2-4天",
      budget: "1500-4000元",
      popularity: 93,
      featured: false,
      image: "https://commons.wikimedia.org/wiki/Special:FilePath/Yalong_Bay%2C_Sanya%2C_Hainan_Island_%2810098713553%29.jpg",
      gallery: [
        "https://commons.wikimedia.org/wiki/Special:FilePath/Yalong_Bay%2C_Sanya%2C_Hainan_Island_%2810098713553%29.jpg",
        "https://commons.wikimedia.org/wiki/Special:FilePath/Yalong_Bay_%E4%BA%9E%E9%BE%8D%E7%81%A3_-_panoramio.jpg",
      ],
      coordinates: { lat: 18.233313, lng: 109.655742 },
      overview:
        "亚龙湾的关键词是海水、沙滩和度假。适合偏休闲型行程，也适合把海边活动和酒店体验排得更松一点。",
      highlights: [
        { name: "海湾沙滩", desc: "适合清晨和黄昏散步拍照。" },
        { name: "水上运动", desc: "浮潜、帆船和摩托艇都很常见。" },
        { name: "酒店海景区", desc: "适合放慢节奏，做度假型停留。" },
      ],
      foods: ["清补凉", "海南鸡饭", "和乐蟹"],
      transport: ["三亚市区打车约 30-40 分钟", "冬季是更舒服的海边时间", "建议带防晒和轻薄外套"],
      tips: ["日晒很强，要认真防晒", "适合和蜈支洲岛一起规划", "风浪大时先看海况"],
      nearby: ["蜈支洲岛", "亚龙湾热带天堂森林公园", "三亚湾"],
      routeType: "sea",
      sources: [
        "Wikimedia Commons 文件页：Yalong Bay, Sanya, Hainan Island (10098713553).jpg",
        "Wikimedia Commons 文件页坐标：18°13'59.927\"N, 109°39'20.675\"E",
      ],
      label: "海滩与度假",
    },
  ],
  comments: [
    {
      id: 1,
      name: "林晚",
      destination: "west-lake",
      rating: 5,
      date: "2026-05-01",
      title: "清晨环湖太舒服了",
      content: "从苏堤走到雷峰塔，清晨光线非常干净，骑行比打车更顺。茶馆也很适合中途停一下。",
    },
    {
      id: 2,
      name: "阿泽",
      destination: "forbidden-city",
      rating: 5,
      date: "2026-04-22",
      title: "讲解器很值",
      content: "中轴线的层次感比想象里更强，提前预约门票后进场很顺。讲解器能把空间关系讲明白。",
    },
    {
      id: 3,
      name: "小岚",
      destination: "gulangyu",
      rating: 4,
      date: "2026-04-16",
      title: "适合慢慢走",
      content: "岛上坡道多，但风景很好。住一晚会比半日游更舒服，傍晚人少的时候最有味道。",
    },
    {
      id: 4,
      name: "北北",
      destination: "li-river",
      rating: 5,
      date: "2026-04-08",
      title: "水墨感特别强",
      content: "早上雾气一上来，漓江的山和水真的像明信片。阳朔那段骑行一定要留时间。",
    },
    {
      id: 5,
      name: "乔木",
      destination: "chengdu-panda",
      rating: 5,
      date: "2026-03-30",
      title: "熊猫早起更活跃",
      content: "九点前到真的有差别。看完熊猫再去吃火锅，行程节奏就很舒服。",
    },
    {
      id: 6,
      name: "海盐",
      destination: "yalong-bay",
      rating: 4,
      date: "2026-03-18",
      title: "适合放空",
      content: "亚龙湾海水颜色很好看，适合慢节奏度假。建议把防晒和遮阳帽提前准备好。",
    },
  ],
  routes: [
    {
      title: "2 天 1 晚 · 城市经典线",
      type: "city",
      days: "2 天",
      summary: "北京故宫 + 杭州西湖，适合第一次看中国经典城市景观。",
      tags: ["文化", "地标", "轻强度"],
      slugs: ["forbidden-city", "west-lake"],
    },
    {
      title: "3 天 2 晚 · 山水慢游线",
      type: "river",
      days: "3 天",
      summary: "桂林漓江 + 阳朔骑行，适合拍照和放慢节奏。",
      tags: ["山水", "骑行", "摄影"],
      slugs: ["li-river"],
    },
    {
      title: "2 天 1 晚 · 海岛度假线",
      type: "sea",
      days: "2 天",
      summary: "鼓浪屿 + 亚龙湾，适合海边散步和度假酒店体验。",
      tags: ["海岛", "度假", "散步"],
      slugs: ["gulangyu", "yalong-bay"],
    },
    {
      title: "1 天 · 亲子动物线",
      type: "family",
      days: "1 天",
      summary: "成都大熊猫基地，上午看熊猫，下午吃成都味道。",
      tags: ["亲子", "动物", "城市"],
      slugs: ["chengdu-panda"],
    },
  ],
  guideTags: [
    "春季赏花",
    "亲子友好",
    "海岛度假",
    "城市文化",
    "山水摄影",
    "周末短途",
  ],
  packing: [
    "身份证与门票预约信息",
    "轻便背包和充电宝",
    "晴雨两用伞",
    "舒适步行鞋",
    "防晒用品",
    "水和小零食",
  ],
  sourceNotes: [
    "图片全部使用 Wikimedia Commons 公开图片链接，便于追溯原始素材来源。",
    "坐标参考 Wikimedia Commons 文件页中的地理信息与公开条目。",
    "页面文案按公开旅游资料整理，尽量贴近真实旅行体验。",
  ],
};
